var success_result = validation({ username: 'abcdef', password:'aaaaaa'});
console.log(success_result.length === 0);
var user_empty = validation({ username: '', password:'aaaa'});
console.log(user_empty[0] === 'usernameを入力して下さい');
var user_too_short = validation({ username: 'a', password:'aaaaaa'});
console.log(user_too_short[0] === 'usernameは2から8文字です');
var user_too_long = validation({ username: 'aaaaaaaaaaaaaaaaaaa', password:'aaaaaa'});
console.log(user_too_long[0] === 'usernameは2から8文字です');
var user_number = validation({ username: '123456', password:'aaaaaaa'});
console.log(user_number[0] === 'usernameに使える文字は英小文字と-(ハイフン)です');
var user_big = validation({ username: 'ABCDeDFD', password:'aaaaaaa'});
console.log(user_big[0] === 'usernameに使える文字は英小文字と-(ハイフン)です');
var password_empty = validation({ username: 'aaa', password:''});
console.log(password_empty[0] === 'Passwordを入力して下さい');
var password_too_short = validation({ username: 'abcdef', password:'aaa'});
console.log(password_too_short[0] === 'Passwordは6から24文字です');
var password_too_long = validation({ username: 'abcdef', password:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'});
console.log(password_too_long[0] === 'Passwordは6から24文字です');
var password_number = validation({ username: 'abcdef', password:'123456a'});
console.log(password_number[0] === 'Passwordに使える文字は英小大文字と-,+,!,@です');
